steps:
# Install node packages
- name: node:14.19.0
  entrypoint: npm
  args: ['install']

# Build productive files
- name: node:14.19.0
  entrypoint: npm
  args: [ 'run', 'build' ]
  env:
    - 'NODE_ENV=production'

# FRONTEND Deploy cloud app frontend
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy","app-${_ENV}.yaml"]

substitutions:
    _ENV: test
options:
   substitution_option: 'ALLOW_LOOSE'